---
wordlists:
  # Each key takes a list of filenames
  path:
    # Directory list
    - lists/path.txt
  extension:
    # File extension list
    - lists/filetype.txt
  filename:
    # Filename list - will be permuted with extension
    - lists/filename.txt
user_agents:
  # List of user agents to attempt to use - not required, a default
  # will be used
  - lists/useragents.txt

user_agent_jitter: 3

#TODO not implemented in config - max number of concurrent sessions
max_concurrent: 10

# The maximum number of directories into which to descend - ie:
# discover at most site.com/lol/butts/derp/
max_depth: 3

# Method with which to discover files - GET, HEAD or "mix". If mix is
# used, a GET or a HEAD will be randomly chosen upon each query.
discovery_method: mix

# A list of objects not to get - can be any full path relative to the root
blacklist:
  - /index.html

#proxies:
#  myproxy:
#    # "any" implies both http and https
#    type: any
#    connect: 127.0.0.1:8080
#  myotherhttpsonlyproxy:
#    type: https
#    connect: 10.0.0.1:8089
